CREATE TABLE [dbo].[inspay_outlet] (
    [id]                   INT            NULL,
    [memid]                VARCHAR (50)   NULL,
    [Mobile]               VARCHAR (15)   NULL,
    [pan]                  VARCHAR (10)   NULL,
    [email]                VARCHAR (50)   NULL,
    [aaadhar]              VARCHAR (50)   NULL,
    [lat]                  VARCHAR (50)   NULL,
    [long]                 VARCHAR (50)   NULL,
    [consent]              VARCHAR (50)   NULL,
    [initiate_statuscode]  VARCHAR (50)   NULL,
    [initiate_actcode]     VARCHAR (50)   NULL,
    [initiate_status]      VARCHAR (50)   NULL,
    [maskedaadhar]         VARCHAR (50)   NULL,
    [otpReferenceID]       VARCHAR (50)   NULL,
    [hash]                 NVARCHAR (MAX) NULL,
    [initiate_timestamp]   VARCHAR (50)   NULL,
    [initiate_ipay_uuid]   VARCHAR (50)   NULL,
    [initiate_orderid]     VARCHAR (50)   NULL,
    [initiate_environment] VARCHAR (50)   NULL,
    [validate_statuscode]  VARCHAR (50)   NULL,
    [validate_actcode]     VARCHAR (50)   NULL,
    [validate_status]      VARCHAR (50)   NULL,
    [outletId]             VARCHAR (50)   NULL,
    [name]                 VARCHAR (50)   NULL,
    [dateOfBirth]          VARCHAR (15)   NULL,
    [gender]               VARCHAR (10)   NULL,
    [pincode]              VARCHAR (50)   NULL,
    [state]                VARCHAR (50)   NULL,
    [districtName]         VARCHAR (50)   NULL,
    [address]              VARCHAR (500)  NULL,
    [profilePic]           VARCHAR (500)  NULL,
    [validate_timestamp]   VARCHAR (50)   NULL,
    [validate_ipay_uuid]   VARCHAR (50)   NULL,
    [validate_orderid]     VARCHAR (50)   NULL,
    [validate_environment] VARCHAR (50)   NULL
);

