CREATE TABLE [dbo].[inspay_aeps] (
    [id]                 INT          IDENTITY (1, 1) NOT NULL,
    [memid]              VARCHAR (50) NULL,
    [outletid]           VARCHAR (50) NULL,
    [bankid]             VARCHAR (50) NULL,
    [Bank Name]          VARCHAR (50) NULL,
    [IFSC]               VARCHAR (50) NULL,
    [lat]                VARCHAR (50) NULL,
    [long]               VARCHAR (50) NULL,
    [mobile]             VARCHAR (50) NULL,
    [amount]             VARCHAR (50) NULL,
    [statuscode]         VARCHAR (50) NULL,
    [actcode]            VARCHAR (50) NULL,
    [status]             VARCHAR (50) NULL,
    [ipayId]             VARCHAR (50) NULL,
    [payableValue]       VARCHAR (50) NULL,
    [transactionValue]   VARCHAR (50) NULL,
    [accountNumber]      VARCHAR (50) NULL,
    [transactionMode]    VARCHAR (50) NULL,
    [opreratorId]        VARCHAR (50) NULL,
    [walletIpayId]       VARCHAR (50) NULL,
    [miniStatement]      VARCHAR (50) NULL,
    [response_timestamp] VARCHAR (50) NULL,
    [ipay_uuid]          VARCHAR (50) NULL,
    [orderid]            VARCHAR (50) NULL,
    [environment]        VARCHAR (50) NULL,
    CONSTRAINT [PK_inspay_aeps] PRIMARY KEY CLUSTERED ([id] ASC)
);

