CREATE TABLE [dbo].[T_CourierOrder] (
    [Order_Id]                 BIGINT          IDENTITY (1, 1) NOT NULL,
    [Item_Detail]              VARCHAR (MAX)   NULL,
    [PickupPointId]            BIGINT          NOT NULL,
    [From_Name]                VARCHAR (100)   NULL,
    [From_PhoneNo]             VARCHAR (20)    NULL,
    [From_Address]             VARCHAR (MAX)   NULL,
    [From_PinCode]             VARCHAR (10)    NULL,
    [From_Gstin]               VARCHAR (20)    NULL,
    [To_Name]                  VARCHAR (100)   NULL,
    [To_Email]                 VARCHAR (150)   NULL,
    [To_PhoneNo]               VARCHAR (20)    NULL,
    [To_Address]               VARCHAR (MAX)   NULL,
    [To_PinCode]               VARCHAR (10)    NULL,
    [To_Gstin]                 VARCHAR (20)    NULL,
    [Total_Quantity]           DECIMAL (18, 2) NULL,
    [Invoice_Value]            DECIMAL (18, 2) NULL,
    [Cod_Amount]               DECIMAL (18, 2) NULL,
    [Our_Order_Id]             VARCHAR (20)    NULL,
    [Item_Breadth]             DECIMAL (18, 2) NULL,
    [Item_Length]              DECIMAL (18, 2) NULL,
    [Item_Weight]              DECIMAL (18, 2) NULL,
    [Item_Height]              DECIMAL (18, 2) NULL,
    [Is_Reverse]               BIT             NULL,
    [Invoice_No]               VARCHAR (10)    NULL,
    [Total_Discount]           DECIMAL (18, 2) NULL,
    [Shipping_Charge]          DECIMAL (18, 2) NULL,
    [Transaction_Charge]       DECIMAL (18, 2) NULL,
    [GiftWarp_Charge]          DECIMAL (18, 2) NULL,
    [Total_Charge]             DECIMAL (18, 2) NULL,
    [Member_Courier_Charge]    DECIMAL (18, 2) NULL,
    [Member_Ser_Charge]        DECIMAL (18, 2) NULL,
    [Member_Net_Charge]        DECIMAL (18, 2) NULL,
    [MemId]                    BIGINT          NULL,
    [EntryDate]                DATETIME        NULL,
    [UpdateDate]               DATETIME        NULL,
    [Api_Tracking_Id]          VARCHAR (20)    NULL,
    [Api_Order_Id]             VARCHAR (20)    NULL,
    [Api_Order_Pk]             VARCHAR (20)    NULL,
    [Api_Manifest_Link]        VARCHAR (MAX)   NULL,
    [Api_Routing_Code]         VARCHAR (20)    NULL,
    [Api_Courier]              VARCHAR (200)   NULL,
    [Api_Dispatch_Mode]        VARCHAR (100)   NULL,
    [Api_Child_WayBill_List]   VARCHAR (MAX)   NULL,
    [Api_Response_Remark]      VARCHAR (500)   NULL,
    [CourierStatus]            INT             DEFAULT ((0)) NULL,
    [Api_CourierId]            BIGINT          NULL,
    [Member_Gst_Charge]        DECIMAL (18, 2) NULL,
    [Track_Url]                VARCHAR (MAX)   NULL,
    [StatusText]               VARCHAR (50)    NULL,
    [Api_Manifest_Link_Img]    VARCHAR (MAX)   NULL,
    [Api_Manifest_Link_Img_V2] VARCHAR (MAX)   NULL,
    [Api_Manifest_Link_Pdf]    VARCHAR (MAX)   NULL,
    CONSTRAINT [PK_T_CourierOrder] PRIMARY KEY CLUSTERED ([Order_Id] ASC)
);

