CREATE TABLE [dbo].[T_Eko_Aeps_Member] (
    [onboarduserid]         BIGINT        IDENTITY (1, 1) NOT NULL,
    [entrydate]             DATETIME      NULL,
    [updatedate]            DATETIME      NULL,
    [user_code]             VARCHAR (20)  NULL,
    [mem_id]                INT           NULL,
    [merchantmobileno]      VARCHAR (20)  NULL,
    [merchantfirstname]     VARCHAR (150) NULL,
    [merchantmiddlename]    VARCHAR (50)  NULL,
    [merchantlastName]      VARCHAR (50)  NULL,
    [merchantpan]           VARCHAR (20)  NULL,
    [merchantemail]         VARCHAR (150) NULL,
    [merchantdob]           VARCHAR (20)  NULL,
    [merchantshopname]      VARCHAR (150) NULL,
    [merchantresiadd]       VARCHAR (MAX) NULL,
    [merchantresicity]      VARCHAR (100) NULL,
    [merchantresistate]     VARCHAR (100) NULL,
    [merchantresipincode]   VARCHAR (10)  NULL,
    [statuscode]            INT           CONSTRAINT [DF_T_Eko_Aeps_Member_status] DEFAULT ((0)) NULL,
    [statustext]            VARCHAR (250) NULL,
    [biometricmodelname]    VARCHAR (100) NULL,
    [biometricdeviceno]     VARCHAR (100) NULL,
    [merchantofficeadd]     VARCHAR (MAX) NULL,
    [merchantofficecity]    VARCHAR (100) NULL,
    [merchantofficestate]   VARCHAR (100) NULL,
    [merchantofficepincode] VARCHAR (100) NULL,
    [merchantproofadd]      VARCHAR (MAX) NULL,
    [merchantproofcity]     VARCHAR (100) NULL,
    [merchantproofstate]    VARCHAR (100) NULL,
    [merchantproofpincode]  VARCHAR (100) NULL,
    [panfilepath]           VARCHAR (250) NULL,
    [aadharfilefrontpath]   VARCHAR (250) NULL,
    [aadharfilebackpath]    VARCHAR (250) NULL,
    [currentScreenNo]       INT           NULL,
    CONSTRAINT [PK_T_Eko_Aeps_Member] PRIMARY KEY CLUSTERED ([onboarduserid] ASC)
);

