CREATE TABLE [dbo].[T_Member_Info] (
    [Meminfo_id]                   INT             IDENTITY (1, 1) NOT NULL,
    [Memid]                        INT             NULL,
    [Meminfo_membertype]           VARCHAR (50)    NULL,
    [Meminfo_profilepic]           VARCHAR (250)   NULL,
    [Meminfo_designation]          VARCHAR (150)   NULL,
    [Meminfo_address]              VARCHAR (255)   NULL,
    [Meminfo_pincode]              INT             NULL,
    [Meminfo_state]                VARCHAR (150)   NULL,
    [Meminfo_whatsappnumber]       BIGINT          NULL,
    [Meminfo_emailid]              VARCHAR (75)    NULL,
    [Meminfo_website]              VARCHAR (255)   NULL,
    [Meminfo_gstin]                VARCHAR (20)    NULL,
    [Meminfo_KYC_aadharno]         VARBINARY (100) NULL,
    [Meminfo_KYC_aadharcopy]       VARCHAR (500)   NULL,
    [Meminfo_KYC_pannumber]        VARCHAR (15)    NULL,
    [Meminfo_KYC_pancopy]          VARCHAR (500)   NULL,
    [Meminfo_KYC_gstcopy]          VARCHAR (150)   NULL,
    [Meminfo_KYC_status]           VARCHAR (1)     NULL,
    [Meminfo_bank_beneficiaryname] VARCHAR (150)   NULL,
    [Meminfo_bank_accountnumber]   VARCHAR (50)    NULL,
    [Meminfo_bank_ifsc]            VARCHAR (50)    NULL,
    [Meminfo_bank_bankname]        VARCHAR (255)   NULL,
    [Meminfo_lastupdateondate]     DATETIME        NULL,
    [Meminfo_lastupdateIP]         VARCHAR (50)    NULL,
    [Organizationname]             VARCHAR (255)   NULL,
    [fblink]                       VARCHAR (500)   NULL,
    [twitterlink]                  VARCHAR (500)   NULL,
    [instagramlink]                VARCHAR (500)   NULL,
    [linkedinlink]                 VARCHAR (500)   NULL,
    [youtubechannellink]           VARCHAR (500)   NULL,
    [googlemaplink]                VARCHAR (500)   NULL,
    [UPIQRcodeimage]               VARCHAR (250)   NULL,
    [Email_Verified]               VARCHAR (1)     NULL,
    [Paytm_wallet_number]          BIGINT          NULL,
    [business_category]            INT             NULL,
    [business_subcategory]         INT             NULL,
    CONSTRAINT [PK_T_Member_Info] PRIMARY KEY CLUSTERED ([Meminfo_id] ASC)
);

