CREATE TABLE [dbo].[T_Recharegerec] (
    [Recid]                   INT             IDENTITY (1, 1) NOT NULL,
    [memcode]                 INT             NULL,
    [apisourceid]             INT             NULL,
    [mobileno]                VARCHAR (20)    NULL,
    [operatorcode]            VARCHAR (50)    NULL,
    [amount]                  DECIMAL (12, 2) NULL,
    [recmedium]               VARCHAR (50)    CONSTRAINT [DF_T_Recharegerec_recmedium] DEFAULT ('app') NULL,
    [reqtime]                 DATETIME        NULL,
    [restime]                 DATETIME        NULL,
    [status]                  VARCHAR (500)   NULL,
    [statusdesc]              VARCHAR (50)    NULL,
    [promo_id]                INT             NULL,
    [IP]                      VARCHAR (50)    NULL,
    [Res_TRNID]               VARCHAR (50)    NULL,
    [Ref_MobileNo]            BIGINT          NULL,
    [get_disc]                DECIMAL (12, 3) NULL,
    [Mem_disc]                DECIMAL (12, 3) NULL,
    [Org_disc]                DECIMAL (12, 3) NULL,
    [StatusCode]              INT             NULL,
    [ClientRefNo]             VARCHAR (20)    NULL,
    [ExtraFieldName1]         VARCHAR (50)    NULL,
    [ExtraFieldValue1]        VARCHAR (50)    NULL,
    [ExtraFieldName2]         VARCHAR (50)    NULL,
    [ExtraFieldValue2]        VARCHAR (50)    NULL,
    [TrnStatusCode]           INT             NULL,
    [TrnStatusMsg]            VARCHAR (500)   NULL,
    [TrnStatus]               VARCHAR (50)    NULL,
    [OprId]                   VARCHAR (50)    NULL,
    [Service_Sub_Category_Id] INT             NULL,
    CONSTRAINT [PK_T_Recharegerec] PRIMARY KEY CLUSTERED ([Recid] ASC)
);

