CREATE TABLE [dbo].[tbl_signup_Log] (
    [id]                 INT           IDENTITY (1, 1) NOT NULL,
    [Res_statuscode]     VARCHAR (50)  NULL,
    [Res_actcode]        VARCHAR (50)  NULL,
    [Res_status]         VARCHAR (50)  NULL,
    [Res_data]           VARCHAR (50)  NULL,
    [Res_aadhaar]        VARCHAR (50)  NULL,
    [Res_otpReferenceID] VARCHAR (50)  NULL,
    [Res_hash]           VARCHAR (500) NULL,
    [Res_timestamp]      VARCHAR (50)  NULL,
    [Res_ipay_uuid]      VARCHAR (50)  NULL,
    [Res_orderid]        VARCHAR (50)  NULL,
    [Res_environment]    VARCHAR (50)  NULL,
    [Req_mobile]         VARCHAR (50)  NULL,
    [Req_email]          VARCHAR (50)  NULL,
    [Req_pan]            VARCHAR (50)  NULL,
    [Userid]             VARCHAR (50)  NULL,
    [Req_Adhaar]         VARCHAR (50)  NULL,
    [Req_longitute]      VARCHAR (50)  NULL,
    [Req_latitude]       VARCHAR (50)  NULL,
    [uniqueid]           VARCHAR (50)  NULL,
    [outletId]           VARCHAR (50)  NULL,
    [name]               VARCHAR (50)  NULL,
    [dateOfBirth]        VARCHAR (50)  NULL,
    [gender]             VARCHAR (15)  NULL,
    [pincode]            VARCHAR (10)  NULL,
    [state]              VARCHAR (50)  NULL,
    [districtName]       VARCHAR (50)  NULL,
    [address]            VARCHAR (500) NULL,
    [profilePic]         VARCHAR (500) NULL,
    CONSTRAINT [PK_tbl_signup_Log] PRIMARY KEY CLUSTERED ([id] ASC)
);

